version: "3.8"

services:
  postgres:
    image: postgres:latest    # 你現成有資料的資料庫 image
    container_name: my-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: barrysu
      POSTGRES_PASSWORD: a22930246
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data    # <<< 掛載 Volume 保留資料
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - backend

  javaapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: myspringboot
    ports:
      - "5000:5000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: barrysu
      SPRING_DATASOURCE_PASSWORD: a22930246
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - backend

volumes:
  postgres-data:     # <<< 這邊定義 Volume
    driver: local

networks:
  backend:
    driver: bridge

