version: '3'
services:
  frontend:
    image: 'barrysu/frontend'
    mem_limit: 128m
    hostname: frontend
    ports:
      - "80:80"   # ← 把 frontend 對外露出 80 port

  backend:
    image: 'barrysu/backend'
    mem_limit: 128m
    hostname: backend
    environment:
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    ports:
      - "5000:5000"  # ← 把 backend 對外露出 5000 port

  nginx:
    image: 'barrysu/nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'

