version: '3'
services:
  frontend:
    image: 'barrysu/frontend'
    mem_limit: 128m
    hostname: frontend
  backend:
    image: 'barrysu/backend'
    mem_limit: 128m
    hostname: backend
    environment:
      - PGUSER="${PGUSER}"
      - PGHOST="${PGHOST}"
      - PGDATABASE="${PGDATABASE}"
      - PGPASSWORD="${PGPASSWORD}"
      - PGPORT="${PGPORT}"
      - REDIS_HOST="${REDIS_HOST}"
      - REDIS_PORT="${REDIS_PORT}"
    restart: always
  nginx:
    image: 'barrysu/nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'

