apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-csi
parameters:
  type: gp3
  fsType: ext4
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
