#name: Deploy MultiDocker
#on:
#  push:
#    branches:
#      - main # check your repo, your default branch might be master!
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
#      # Frontend test image (Angular)
#      - run: docker build -t barrysu/frontend-test -f ./complex_frontend/Dockerfile.test ./complex_frontend
#      - run: docker run barrysu/frontend-test npm run test -- --watch=false --browsers=ChromeHeadlessNoSandbox
#
#      # Backend test image (Spring Boot)
#      - run: docker build -t barrysu/backend-test -f ./complex_backend/Dockerfile.test ./complex_backend
#      - run: docker run barrysu/backend-test mvn test
#
#
#      - run: docker build -t barrysu/backend ./complex_backend
#      - run: docker build -t barrysu/frontend ./complex_frontend
#      - run: docker build -t barrysu/nginx ./nginx
#
#      - run: docker push barrysu/backend
#      - run: docker push barrysu/frontend
#      - run: docker push barrysu/nginx
#
#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'
#
#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: multi-docker
#          environment_name: Multi-docker-env
#          existing_bucket_name: elasticbeanstalk-ap-northeast-1-209479294288
#          region: ap-northeast-1
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip


name: CI/CD with Docker Hub and AWS EKS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Git SHA as image tag
        id: vars
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker build -t barrysu/frontend:${GIT_SHA} ./complex_frontend
          docker build -t barrysu/backend:${GIT_SHA} ./complex_backend
          docker push barrysu/frontend:${GIT_SHA}
          docker push barrysu/backend:${GIT_SHA}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.29.0'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-1

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-northeast-1 --name k8s1

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/
          kubectl set image deployment/frontend-deployment frontend=barrysu/frontend:${GIT_SHA}
          kubectl set image deployment/backend-deployment backend=barrysu/backend:${GIT_SHA}
